
kind: pipeline
name: default
type: kubernetes
steps:

  - name: update manifest
    image: quay.io/ukhomeofficedigital/asl-deploy-bot:latest
    environment:
      GITHUB_ACCESS_TOKEN:
        from_secret: github_access_token
    commands:
      - update
        --repo ukhomeoffice/asl-deployments
        --token $${GITHUB_ACCESS_TOKEN}
        --file versions.yml
        --service asl
        --version $${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master
